// This file was auto-generated by ML.NET Model Builder. 

using Microsoft.ML.Data;

namespace CombiConML.Model
{
    public class ModelInput
    {
        [ColumnName("previousHit"), LoadColumn(0)]
        public float PreviousHit { get; set; }


        [ColumnName("newHit"), LoadColumn(1)]
        public float NewHit { get; set; }


        [ColumnName("directionChanged?"), LoadColumn(2)]
        public bool DirectionChanged_ { get; set; }


    }
}
